---
apiVersion: v1
kind: Pod
metadata:
  name: gcc-runner
  labels:
    name: gcc-runner
spec:
  containers:
  - name: gcc-runner
    image: gcc
    command:
        - "sh"
        - "-c"
        - "while true; do sleep 3600; done"
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
